version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: parcel
    versions:
    - 2.0.0-nightly.554
    - 2.0.0-nightly.560
    - 2.0.0-nightly.562
    - 2.0.0-nightly.566
    - 2.0.0-nightly.570
    - 2.0.0-nightly.573
    - 2.0.0-nightly.574
    - 2.0.0-nightly.577
    - 2.0.0-nightly.579
    - 2.0.0-nightly.585
    - 2.0.0-nightly.596
    - 2.0.0-nightly.597
    - 2.0.0-nightly.598
    - 2.0.0-nightly.600
    - 2.0.0-nightly.605
    - 2.0.0-nightly.606
    - 2.0.0-nightly.607
    - 2.0.0-nightly.608
    - 2.0.0-nightly.609
    - 2.0.0-nightly.610
    - 2.0.0-nightly.614
    - 2.0.0-nightly.615
    - 2.0.0-nightly.619
    - 2.0.0-nightly.620
    - 2.0.0-nightly.623
    - 2.0.0-nightly.626
    - 2.0.0-nightly.627
    - 2.0.0-nightly.628
    - 2.0.0-nightly.630
    - 2.0.0-nightly.631
    - 2.0.0-nightly.632
    - 2.0.0-nightly.634
    - 2.0.0-nightly.635
    - 2.0.0-nightly.636
    - 2.0.0-nightly.637
    - 2.0.0-nightly.639
    - 2.0.0-nightly.640
    - 2.0.0-nightly.641
    - 2.0.0-nightly.643
    - 2.0.0-nightly.644
    - 2.0.0-nightly.646
  - dependency-name: acorn
    versions:
    - 8.1.0
    - 8.1.1
    - 8.2.1
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.12
    - 8.2.4
    - 8.2.5
    - 8.2.6
    - 8.2.7
    - 8.2.8
    - 8.2.9
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
    - 8.2.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: stylelint
    versions:
    - 13.10.0
    - 13.11.0
    - 13.12.0
    - 13.9.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: pug
    versions:
    - 3.0.1
  - dependency-name: pug-code-gen
    versions:
    - 3.0.2
  - dependency-name: sass
    versions:
    - 1.32.5
    - 1.32.6
    - 1.32.7
    - 1.32.8
  - dependency-name: autoprefixer
    versions:
    - 10.2.3
    - 10.2.4
